<a href="https://colab.research.google.com/github/kkhurana82/LearningPytorch/blob/main/notebooks/pytorch_pipeline_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ## ** Pytorch pipeline using NN module**

In [326]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        z = self.linear(features)
        out = self.sigmoid(z)
        return out


In [327]:
# create fake dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call ffd pass

out = model(features)


In [328]:
out

tensor([[0.4789],
        [0.4254],
        [0.4507],
        [0.4958],
        [0.4346],
        [0.5192],
        [0.4226],
        [0.5615],
        [0.4298],
        [0.5154]], grad_fn=<SigmoidBackward0>)

In [329]:
model.linear

Linear(in_features=5, out_features=1, bias=True)

In [330]:
model.linear.bias

Parameter containing:
tensor([-0.0327], requires_grad=True)

In [331]:
model.linear.in_features

5

In [332]:
model.linear.out_features

1

In [333]:
!pip install torchinfo

In [334]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.3354, -0.2314, -0.3737,  0.3587, -0.1923]], requires_grad=True)

In [335]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [336]:
# new model with hiddel layer and ReLu

class Model2(nn.Module):
    def __init__(self, num_features):
        super(Model2, self).__init__()
        self.input = nn.Linear(num_features,5)
        self.relu = nn.ReLU()
        self.hiddel1 = nn.Linear(5,3)
        self.output = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.input(features)
        out = self.relu(out)
        out = self.hiddel1(out)
        out = self.output(out)
        out = self.sigmoid(out)
        return out


In [337]:

features = torch.rand(10,5)

model2 = Model2(features.shape[1])

## ffd pass
out = model2(features)

In [338]:
out

tensor([[0.5534],
        [0.5464],
        [0.5563],
        [0.5506],
        [0.5570],
        [0.5506],
        [0.5458],
        [0.5512],
        [0.5480],
        [0.5462]], grad_fn=<SigmoidBackward0>)

In [339]:
model2.input.weight

Parameter containing:
tensor([[ 0.1588, -0.4016,  0.4420, -0.1765,  0.0661],
        [-0.3431, -0.4049,  0.3844, -0.1844,  0.3034],
        [ 0.2325, -0.0791, -0.1632, -0.3330,  0.1506],
        [ 0.1012,  0.2557,  0.2801, -0.3008,  0.0209],
        [ 0.4399,  0.3072, -0.4199,  0.3050,  0.2748]], requires_grad=True)

In [340]:
model2.hiddel1.weight

Parameter containing:
tensor([[-0.1456,  0.0608,  0.3667, -0.1778, -0.4104],
        [-0.3962,  0.2587, -0.1091,  0.2341, -0.3852],
        [ 0.0445, -0.1235, -0.0350,  0.3638,  0.1256]], requires_grad=True)

In [341]:
model2.output.weight

Parameter containing:
tensor([[ 0.0917, -0.2625,  0.5389]], requires_grad=True)

In [342]:
summary(model2,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 5]                   30
├─ReLU: 1-2                              [10, 5]                   --
├─Linear: 1-3                            [10, 3]                   18
├─Linear: 1-4                            [10, 1]                   4
├─Sigmoid: 1-5                           [10, 1]                   --
Total params: 52
Trainable params: 52
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [343]:
# new model with sequential container

class Model3(nn.Module):
    def __init__(self, num_features):
        super(Model3, self).__init__()
        self.network = nn.Sequential(
          nn.Linear(num_features,5),
          nn.ReLU(),
          nn.Linear(5,3),
          nn.Linear(3,1),
          nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)

        return out

In [344]:

features = torch.rand(10,5)

model3 = Model3(features.shape[1])

## ffd pass
out = model3(features)

In [345]:
model3.network

Sequential(
  (0): Linear(in_features=5, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=1, bias=True)
  (4): Sigmoid()
)

In [346]:
model3.network[0].weight

Parameter containing:
tensor([[ 0.1645, -0.2781, -0.1819,  0.3901, -0.0789],
        [-0.2826,  0.4211,  0.2694, -0.1124, -0.0359],
        [-0.1706, -0.3545, -0.3828, -0.2541, -0.0554],
        [ 0.1664, -0.4009, -0.1028,  0.2776, -0.0140],
        [ 0.3776,  0.1399, -0.3661, -0.3621,  0.1460]], requires_grad=True)

## Breast cancer prediction using public dataset

In [347]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [348]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [349]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [350]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [351]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [352]:
X_train

array([[-1.58060136, -1.73569184, -1.56895979, ..., -1.09441785,
         0.48051165,  0.30026408],
       [-0.87566056, -1.06335536, -0.90984563, ..., -1.11143447,
        -1.59984145, -0.6224702 ],
       [-0.12834314, -0.75021234, -0.177635  , ..., -0.70770404,
         0.64308856, -0.41346792],
       ...,
       [-1.0216881 , -0.23214484, -1.05063939, ..., -1.42526296,
        -0.34184341, -0.93328029],
       [ 0.37845833, -1.71266662,  0.43122534, ...,  0.99139717,
         0.47419798,  0.878791  ],
       [ 0.13794238,  1.08029281,  0.10187592, ..., -0.71387821,
        -0.62122315, -0.6585608 ]])

In [353]:
y_train

59     B
173    B
374    B
413    B
445    B
      ..
549    B
5      M
443    B
172    M
90     B
Name: diagnosis, Length: 455, dtype: object

In [354]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [355]:
y_train

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,

In [356]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [357]:
X_train_tensor.shape

torch.Size([455, 30])

In [358]:
y_train_tensor.shape

torch.Size([455])

In [359]:
learning_rate = 0.1
epochs = 100

In [360]:
# define loss function
loss_function = nn.BCELoss()

In [361]:
# create model
model = Model3(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.reshape(-1, 1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.8511942625045776
Epoch: 2, Loss: 0.8235855102539062
Epoch: 3, Loss: 0.8014426231384277
Epoch: 4, Loss: 0.7831091284751892
Epoch: 5, Loss: 0.7675375938415527
Epoch: 6, Loss: 0.7539842128753662
Epoch: 7, Loss: 0.7420557141304016
Epoch: 8, Loss: 0.7312700152397156
Epoch: 9, Loss: 0.7213302850723267
Epoch: 10, Loss: 0.7120783925056458
Epoch: 11, Loss: 0.7033014893531799
Epoch: 12, Loss: 0.6948765516281128
Epoch: 13, Loss: 0.6865808367729187
Epoch: 14, Loss: 0.6782851815223694
Epoch: 15, Loss: 0.669774055480957
Epoch: 16, Loss: 0.6609493494033813
Epoch: 17, Loss: 0.6517094969749451
Epoch: 18, Loss: 0.6420710682868958
Epoch: 19, Loss: 0.6319270730018616
Epoch: 20, Loss: 0.6212489604949951
Epoch: 21, Loss: 0.6098093390464783
Epoch: 22, Loss: 0.5975912809371948
Epoch: 23, Loss: 0.5845947265625
Epoch: 24, Loss: 0.570661187171936
Epoch: 25, Loss: 0.5557900071144104
Epoch: 26, Loss: 0.5400490760803223
Epoch: 27, Loss: 0.5234906673431396
Epoch: 28, Loss: 0.5062297582626343
Epoch:

In [362]:
model.network

Sequential(
  (0): Linear(in_features=30, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=1, bias=True)
  (4): Sigmoid()
)

In [363]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.8).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.55755615234375
